### ISSUE TITLE
Error upon adding an item

### ISSUE THREAD

**Issue by bvdputte** [sylvainjule/kirby-categories#3]
Just checking out your plugin, and when I try to add a (second) item to the categories field; I get an error: `Cannot read property '0' of undefined`?

Tried in a fresh starterkit with Kirby 3.5.3

**Comment by sylvainjule** [comment]
Works fine up to 3.4.5. Then it breaks in 3.5.0, not sure why yet... Possibly because vue was updated from 2.6.11 to 2.6.12, possibly because of something else... but I haven't been able to figure it out yet.

**Comment by bvdputte** [comment]
Yea, it's weird. And not a very descriptive error neither 😐

**Comment by sylvainjule** [comment]
I get what's happening though (The DOM seems not to have been updated by the time I try to call `focus()` on the newly added input. But that's what `this.$nextTick(callback)` is supposed to help with, and helped with successfully until 3.5...).

I've asked on the vue channel on the discord, in case someone can help with this.

**Comment by sylvainjule** [comment]
Was my fault! It's now fixed.

**Comment by sylvainjule** [comment]
I tweaked a bit the way the data is structured though, see: https://github.com/sylvainjule/kirby-categories/releases/tag/1.0.0
